debug again

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -90,4 +90,4 @@ jobs:
           cat .minecraft/versions/CI/logs/latest.log
           ls -n .minecraft/versions/CI/logs/
           ls -n .minecraft/versions/CI/
-          if [ `grep -c "java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init" .minecraft/versions/CI/logs/latest.log` -ne "1" ]; then echo "::error title=Game crashed::Oops." && exit 1; fi
+          if [ `grep -c "java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init" .minecraft/versions/CI/crash-reports/crash-*-client.txt` -ne "1" ]; then echo "::error title=Game crashed::Oops." && exit 1; fi
